@startuml

[*] --> Borrador

Borrador --> Validado : sin conflictos

Borrador --> Borrador : con conflictos

Validado --> Publicado
Publicado --> Borrador : requiere cambios

Publicado --> [*]
@enduml