@startuml

[*] --> Creada

Creada --> Validacion <<choice>>

Validacion --> Resolucion <<choice>>

Resolucion --> Aprobada : solucion aplicada
Resolucion --> Rechazada : no aplicable

Aprobada --> [*]
Rechazada --> [*]
@enduml