@startuml

hide empty description

state EnEdicion
state Validando
state Validado
state Publicado
state Finalizado
state choice1 <<choice>>
state choice2 <<choice>>

[*] --> EnEdicion

EnEdicion --> Validando : Guardar/Validar horario
Validando --> choice1
choice1 --> EnEdicion : Conflictos detectados (alerta)
choice1 --> Validado : Sin conflictos

Validado --> Publicado : Guardar cambios (publicar)
Publicado --> choice2

choice2 --> EnEdicion : Modificar / Reactivar (usuario)
choice2 --> Finalizado : Cierre definitivo (usuario)

Finalizado --> [*]

@enduml
